### ISSUE TITLE
SMem显存占用

### ISSUE THREAD

**Issue by hmeng7710** [xmed-lab/AllSpark#11]
请问一下SMem会造成多大的资源占用？以及队列大小对结果的影响。

**Comment by McGregorWwww** [comment]
你好，SMem大约占用630M的显存，队列大小的影响可以参考论文的supplement material。
<img width="836" alt="image" src="https://github.com/xmed-lab/AllSpark/assets/35693095/3a57c117-b4fb-437a-98c6-1e19e271d47d">

**Comment by hmeng7710** [comment]
感谢您的耐心回复，我还有一个问题，就是看到你不同数据集训练的log日志中参数都不太相同，请问一下能不能给出一个详细的每个数据集不同划分具体应该怎么设置的文档呢？seed在哪里设置以及temperature？
