### ISSUE TITLE
cross_attn_l2u的计算方式

### ISSUE THREAD

**Issue by feihongyan1** [xmed-lab/AllSpark#14]
想问下代码中cross_attn_l2u的计算方式能否更详细的讲解一下. 初步看似乎不是计算通道之间的相似度而是在计算token之间的相似度.不知道我的理解对不对. 如果可以的话是否能够加微信联系一下, 我微信18842363882.

**Comment by McGregorWwww** [comment]
你好，抱歉回复的有点晚了，通道相似度的操作主要是通过转置实现的，原本是q (B, N, C) * k^T (B, C, N) 得到 (N, N)的相似性矩阵，通道的话就是q^T (B, C, N) * k (B, N, C) 得到 (C，C)的相似性矩阵，即每个channel的之间的关系，希望有帮助

**Comment by feihongyan1** [comment]
感谢, 稍后我再去学习下~.
