### ISSUE TITLE
关于cityscapes数据集

### ISSUE THREAD

**Issue by KeyWu** [xmed-lab/AllSpark#15]
请问一下能否提供完整的训练日志可供参考？训练完240epoch大概用时以及bs设置？

**Comment by McGregorWwww** [comment]
你好，因为服务器原因，代码修正后还没重新训练完，训练日志后面会更新，用四张A100 40G训练完大概1天，bs=2

**Comment by Fly-Yun-Maker** [comment]
您好，请问Cityscapes数据集的训练日志更新好了嘛
