### ISSUE TITLE
How much memory its necessary?

### ISSUE THREAD

**Issue by EduardoLawson1** [xmed-lab/AllSpark#2]
Great work guys! I would like to know how much memory its necessary to train?

**Comment by McGregorWwww** [comment]
Hi, thanks for your interest of our work.

Regarding the training memory, please refer to this issue: https://github.com/LiheYoung/UniMatch/issues/39. AllSpark requires approximately 10% more memory compared to UniMatch because we use ViTs and a memory bank to store unlabeled features.
