### ISSUE TITLE
install mmcv encounter: python setup.py eggs error, subprocess exited  and metadata generation failed

### ISSUE THREAD

**Issue by mmcvers** [xmed-lab/AllSpark#4]
thanks for your work ,it's actually details.I followed your readme and install necessary package by sequence.but enconter the error:
<img width="357" alt="egg_info" src="https://github.com/xmed-lab/AllSpark/assets/166209741/ce17943e-0057-4188-9383-d0db25b91e6d">

I try some solutions such as pip install pip upgrade pip setuptools contain uninstall and install ,and I confirm the config path of cuda in bashrc contain CUDA_Home and LD_LIBRARY ,which point to the folder that contain bin lib and include in my conda envs .Due to the fault in the base env is not exist , I guess that is not related to the cuda .But the gpt suggest that base env has not cuda so that don't affect the installation of mmcv.Besides,the version of mmcv I get it's match your readme called 1.6.2 from https://pypi.tuna.tsinghua.edu.cn/simple to faster.About the cuda, due to it's binding to the torch so that .so called libtorch_cuda.so.In my a test.py in Generic_ssl,I use the ctypes..CDLL(library_path) to load them, and in the mmcv setup.py its seems so complicated.
Looking forward to hearing from your reply!

**Comment by McGregorWwww** [comment]
Hi, maybe you can try to install mmcv from source: https://mmcv.readthedocs.io/en/latest/get_started/build.html. 

Hope this helps.
