### ISSUE TITLE
when will the final version release? 

### ISSUE THREAD

**Issue by ganliqiang** [xmed-lab/AllSpark#5]
when will the final version release?  i am very instreast in your reasearch work because of the excellent result on the leadboad.but sadly the code is not ready for use, do you any plan about when the final version will be released?

**Comment by McGregorWwww** [comment]
Hi, thanks for your interest of our work. We are currently rerunning and checking other parts of the codes for potential mistakes. If everything goes well, the final version will be released within two weeks.

**Comment by hn9840** [comment]
Hi, do you have any updates? We are looking forward to using your final code. Thank you very much!
