### ISSUE TITLE
编码器和解码器问题

### ISSUE THREAD

**Issue by cvazhe** [xmed-lab/AllSpark#7]
作者您好，请问我想尝试将编码器换成Resnet50/101,解码器换成deeplabv3+。这需要更改哪里呀！

**Comment by Elliot-QxZhang** [comment]
非常感谢对我们的工作感兴趣，这个可以在config文件中进行修改，比如如果需要将backbone换成Resnet50的话，需要将config文件中的model字段进行以下修改：

model:
  backbone:
    type: model.backbone.resnet.resnet50
  decoder:
    type: model.semseg.allspark.SemiDecoder
    kwargs:
      num_heads: 2
      num_class: 21
      in_planes: [64, 128, 320, 512]
      image_size: 513
      warmup_epoch: 5
      embedding_dim: 768

如果需要将整个decoder，包括我们的allspark模块全部换掉的话，可以使用我们的[train_baseline_semi.py](https://github.com/xmed-lab/AllSpark/blob/main/train_baseline_semi.py),将config中的decoder字段换掉，也可以参考https://github.com/LiheYoung/UniMatch
