### ISSUE TITLE
训练时出现问题

### ISSUE THREAD

**Issue by Dzrb** [xmed-lab/AllSpark#8]
[20240429_205311.log](https://github.com/xmed-lab/AllSpark/files/15183897/20240429_205311.log)
您好，如log文件所示，在训练到21epoch时，突然出现损失函数变大，性能下降的问题，请问这是否属于正常现象？

**Comment by Dzrb** [comment]
您好，你们在实验时有发现这样的问题吗

**Comment by hmeng7710** [comment]
我也遇到了和你同样的问题。

**Comment by hmeng7710** [comment]
请问一下问题您有没有解决？可以的话方便加个联系方式一起沟通吗
