### ISSUE TITLE
AllSpark中的InstanceNorm和cross attention

### ISSUE THREAD

**Issue by zdk258** [xmed-lab/AllSpark#9]
感谢出彩的工作！
代码AllSpark中有一个InstanceNorm层
`self.psi = nn.InstanceNorm2d(self.num_heads)`
请问为什么用InstanceNorm以及为什么参数设置为num_heads呢？
```
k_l2u = rearrange(k_l2u, 'b n c -> n (b c)')
v_l2u = rearrange(v_l2u, 'b n c -> n (b c)')

k_l2u = repeat(k_l2u, 'n bc -> r n bc', r=batch_size)
v_l2u = repeat(v_l2u, 'n bc -> r n bc', r=batch_size)
```
还有cross attention中的这一段代码是什么作用呢？

**Comment by McGregorWwww** [comment]
你好，感谢关注。InstanceNorm的作用主要就是normalization，用来替代原始attention中的/√d，原因是我们发现在channel-wise attention中这样做能更好的解决梯度消失问题；因为所使用的attention是多头，所以设置num_heads对每个头分别进行normalization。这段代码是为了将当前batch里的所有unlabeled features对应给每一个labeled sample，所以对unlabeled进行了batch_size的堆叠。

**Comment by zdk258** [comment]
感谢回复。
